### PR TITLE
Add my contributions.md and contributing guidelines

### LINKED ISSUE #15: Add a Contributing.md file for guiding users on how to setup locally
We could add a Contributing.md file wherein we could guide newcomers to set up this repo locally on their machine and could also guide them on how they could make a pr or contribute by helping them with all the commands and how the command works .

### PR DESCRIPTION
**Pull request by m-code12**
Fixes #15
I have added my folder and named it as 'Monika Jha' and created a contributions.md file in it.

### CODE REVIEW

**Comment by m-code12** [comment]
I have added Conributing Guidelines for issue #15 . Please review and merge @pbteja1998

**Comment by me-diru** [comment]
Add steps to steup the repo locally as well

**Comment by m-code12** [comment]
@diru1100 Yes I have added

**Comment by me-diru** [comment]
You haven't written the steps to run it locally, add them as well.

**Comment by m-code12** [comment]
Which steps/commands are you talking about ? @diru1100 
Sorry I didn't get it .

**Comment by me-diru** [comment]
The steps to run the projects in localhost i.e how to run the application locally and what all commands are required to do that. The steps you wrote are generic to any project in GitHub.

**Comment by m-code12** [comment]
Made the changes @diru1100 .Please could you review it and merge this pr.

**Comment by me-diru** [comment]
Yup, Looks good

**Pull request merged**
